### ISSUE TITLE
In Microsoft Edge has issue^(

### ISSUE THREAD

**Issue by Venegrad** [HTML50/cubeTransition.js#3]
In any version ms edge, slider work not correctrly :(

**Comment by HTML50** [comment]
@Venegrad
Hi
does the demo page work fine?
I'm using Microsoft Edge 40.15063.674.0 and all goes right.

**Comment by HTML50** [comment]
@Venegrad 
show me your code

**Comment by Venegrad** [comment]
Hi. Demo has this error too :(
https://www.youtube.com/watch?v=SWW0bvJO2RU

**Comment by HTML50** [comment]
Hi @Venegrad 
I have watched your video. 
I can not get a MS Edge 41.16299 and I double checked CSS source, finding nothing wrong I think.
you can try this site http://rdcm.com in Edge to see if its animation goes right.
#1 has the exactly same animtaion problem as I saw in your video, but I think I fixed it.
anyway,  I have updated this Demo for you, try to see is there anything improved.

**Comment by Venegrad** [comment]
Ye on http://rdcm.com all work fine, this site has no error, but demo still has error.

**Comment by HTML50** [comment]
@Venegrad 
try this test page use UP and DOWN key to switch.
http://es5.site/cubeTransition.js/test.html
If it doesn't work...
I will fix it until I get a Edge ver 41

**Comment by Venegrad** [comment]
still has error (

**Comment by HTML50** [comment]
@Venegrad 
sorry for cannot help you, I dont know what goes wrong only if I got a new version Edge.

but you can try to modify the `style.css` by yourself.
```CSS
@keyframes rotateCubeTopOut {
  50% {
      transform: translateY(-50%) translateZ(-200px) rotateX(45deg);
  }

  100% {
    transform: translateY(-100%) rotateX(90deg); 
  }
  
}
```
you can try to change 100% { `translateY(-100%)` } 
to `translateY(-80%)`  to see if animation works better.
